user:
  maximum: 60
  minimum: 6
  remember: 1
  avatar: https://secure.gravatar.com/avatar/#{gravatar_id}
  edit_avatar: http://gravatar.com/emails
  supervisor: 1
  notsupervisor: 0
  per_page: 10
course:
  status:
    - Start
    - Finished
subject:
  finish: Finished
  status:
    - Start
    - Finished
  user:
    - Start
    - Training
    - Finished
activity:
  learn: Started
  joined: Joined
  start: Start
  done: Done
  training: training
