user:
  maximum: 60
  minimum: 6
  remember: 1
  avatar: https://secure.gravatar.com/avatar/#{gravatar_id}
  edit_avatar: http://gravatar.com/emails
  supervisor: 1
  notsupervisor: 0
subject:
  finish: Finished
  status:
    - Start
    - Finished
